version: '3.8'
services:
  app:
    build:
      context: .
      args:
        - VITE_TMDB_API_KEY=${VITE_TMDB_API_KEY}
    ports:
      - "3999:3999"
    environment:
      - VITE_TMDB_API_KEY=${VITE_TMDB_API_KEY}